### ISSUE TITLE
Table cells with &nbsp; as the only content shouldn't be an error

### ISSUE THREAD

**Issue by a2sheppy** [Elchi3/mdn-doc-tests#133]
Currently, this generates an "empty element" error, but this is an intentional construct used when a table cell has no value.

**Comment by SebastianZ** [comment]
This also bugs me sometimes, though the cases where I saw this so far were always missing information, e.g. an empty comment cell within the specifications table. (The indication might be changed to a warning instead of an error in this case, though.)
Do you have an example for where the table cell should stay empty?

Sebastian

**Comment by a2sheppy** [comment]
Yeah. Sometimes there are "Additional comments" or "Exceptions" or the
like columns in tables which only occasionally have any data in them.
I've seen a few of them lately.

**Comment by SebastianZ** [comment]
So, as [suggested above](https://github.com/Elchi3/mdn-doc-tests/issues/133#issuecomment-189143078), considering that there are cases in which it is required to fill in something, like the specifications or browser compatibility tables, for example, this should be changed to a warning.

Because there are other cases of empty elements, which **are** errors, this requires issue #52 to be implemented first.

Sebastian

**Comment by Elchi3** [comment]
I think changing this to a warning would be cool as a quick next step.

**Comment by SebastianZ** [comment]
> I think changing this to a warning would be cool as a quick next step.

It will be quite easy to do only for &nbsp;s in table cells (and keep the other empty elements as errors) once https://github.com/Elchi3/mdn-doc-tests/pull/151 is merged.

Sebastian
