### ISSUE TITLE
Turn extension into WebExtension

### ISSUE THREAD

**Issue by SebastianZ** [Elchi3/mdn-doc-tests#231]
The extension currently based on the Add-on SDK needs to be turned into a WebExtension. 

After all blockers from issue #181 are implemented, work on this can start.

Sebastian

**Comment by Elchi3** [comment]
Thanks Sebastian. As mentioned in the other issue: If Mozilla is accepted for GSOC, I will mentor this project, so please anyone who is interested in working on this: please hold for now.
https://wiki.mozilla.org/Community:SummerOfCode17:Brainstorming#Mozilla_Developer_Network

**Comment by a2sheppy** [comment]
We should consider the possibility of building it into MDN instead of using an extension. It could be built as a CKEditor plugin, which would give it closer access to the data, likely making certain parts of the manipulation of the content easier and more reliable. More importantly, though, it would mean that all MDN contributors would have it, instead of just those who care enough to install the extension. This is especially useful since many of the mistakes are made by one-time or new MDN contributors, who certainly won't have the extension installed.

**Comment by SebastianZ** [comment]
I really like that idea!
I assume this requires some more resources and also some UI reworking. As that sounds to be out of the scope of this issue tracker, should we file a bug for this in Bugzilla?

Sebastian

**Comment by a2sheppy** [comment]
Obviously, that depends on Florian and his student to determine -- I don't even know if Florian thinks this is a candidate for the GSOC effort or not, although it could be.

**Comment by Elchi3** [comment]
The GSOC project is accepted. I have had several discussions with many students and have worked out different project plans. It will be a GSOC 2017 project, I will pick a student soon, and there will be (a) new repository/ies. You can file in Bugzilla but it is very likely that we will work on this project on GitHub repos and issues in the future.
One thing that came out of the discussions is that we want to separate testing/linting from UIs, so that testing could be in an extension, or in the editor, or on the server-side in the future. Stay tuned as GSOC proceeds.

**Comment by SebastianZ** [comment]
I've filed [bug 1352844](https://bugzilla.mozilla.org/show_bug.cgi?id=1352844).

Sebastian

**Comment by Elchi3** [comment]
GSOC is underway and work on the WebExtension can be followed in this repository https://github.com/mdn/doc-linter-webextension

**Comment by Elchi3** [comment]
There is a first beta WebExtension version available and we've also put the rules into a separate repository, so they can be used in CKEditor or on the server side in the future. Please follow these two repos now:
https://github.com/mdn/doc-linter-webextension
https://github.com/mdn/doc-linter-rules
