### ISSUE TITLE
Split tests into their own files

### ISSUE THREAD

**Issue by Elchi3** [Elchi3/mdn-doc-tests#88]
While reviewing PR #87, it becomes quite hard to give every test a solid review, because the two files doctests.js and test-doctests.js are quite long nowadays. I think it makes sense to have 1 file for 1 test and have the test object along with the unit test for it in one file. Also, it would be nice to avoid some merge conflicts in the future.
This way test-doctests.js can concentrate on executing the tests (which has become more complex in that PR, too).

Maybe the object could look like this:

<pre>
"oldURLs": {
    name: "old_en_urls",
    desc: "old_en_urls_desc",
    check: function checkOldURLs(rootElement) {
      var links = rootElement.querySelectorAll("a[href]");
      var matches = [];
      for (var i = 0; i < links.length; i++) {
        // This check can be removed once querySelectorAll supports case-insensitive search, i.e. a[href^='/en/' i]
        if (links[i].getAttribute("href").match(/^\/en\//i)) {
          matches.push({
            msg: links[i].outerHTML
          });
        }
      }
      return matches;
    },
    type: ERROR,
    errors: []
    tests: = [{
      str:  // ...
      expected: [
      // ...
     ]
   }];
 };
</pre>

Thoughts @SebastianZ ?

**Comment by SebastianZ** [comment]
> While reviewing PR #87, it becomes quite hard to give every test a solid review, because the two files doctests.js and test-doctests.js are quite long nowadays. I think it makes sense to have 1 file for 1 test 

I agree.

> and have the test object along with the unit test for it in one file.

I'm not convinced on that. I believe the tests and the unit tests should be separate. Though I agree that each test should be in its own file.
I am thinking of having one file for each test in a new folder `/data/tests/` and a folder `/test/tests/` containing one file for each unit test.

> Also, it would be nice to avoid some merge conflicts in the future.

Absolutely! That becomes quite annoying with the time. Splitting them up will surely mitigate that problem a lot.

> This way test-doctests.js can concentrate on executing the tests (which has become more complex in that PR, too).

Right, it became more complex due to the new requirement that they need to be executed in the page's context. So, splitting the execution logic from the tests themselves makes sense.

Sebastian

**Comment by Elchi3** [comment]
> I'm not convinced on that. I believe the tests and the unit tests should be separate. Though I agree that each test should be in its own file.
> I am thinking of having one file for each test in a new folder /data/tests/ and a folder /test/tests/ containing one file for each unit test.

This would work as well and keeps separating code and test code. Sounds good to me.

**Comment by Elchi3** [comment]
Done in Pull requests #93 and #94

**Comment by SebastianZ** [comment]
\o/
